# Generated by Django 5.2.8 on 2025-11-19 04:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('alert_type', models.CharField(choices=[('warning', 'Предупреждение'), ('danger', 'Опасность'), ('info', 'Информация'), ('success', 'Успех')], default='warning', max_length=20, verbose_name='Тип предупреждения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Баннер предупреждения',
                'verbose_name_plural': 'Баннеры предупреждений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='advertisements/videos/', verbose_name='Видео файл')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='advertisements/thumbnails/', verbose_name='Превью')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('display_order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Видео объявление',
                'verbose_name_plural': 'Видео объявления',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
