# Generated by Django 5.2.8 on 2025-11-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alertbanner_videoadvertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoadvertisement',
            name='thumbnail',
        ),
    ]
